spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true

mybatis:
  type-aliases-package: com.yangman.springbootdemo.bean
  mapper-locations: classpath:mapper/*.xml